### ISSUE TITLE
Double definition

### ISSUE THREAD

**Issue by bhlbarxios** [opcoach/jagsy#15]
A variable name can't be defined twice in a same model
model{
	for(j in 1:M){
	  for(i in 1:N){
	    a[j,i] ~ dnorm(mu,tau)
	  }
	}
	tau ~ dgamma(0.01,0.01)
	mu ~ dnorm(0,1)
	mu ~ dnorm(5,10)
}

**Comment by opcoach** [comment]
I added a validator to start to validate the contents. 
Unit tests are also started !
