### ISSUE TITLE
Optional data section not allowed in the grammar syntax

### ISSUE THREAD

**Issue by bhlbarxios** [opcoach/jagsy#18]
A model definition might contain a data section in addition to the model section. Currently, the data section is tagged as an error....

data {
  D <- dim(Z)
}

model{
	for(j in 1:M){
	  for(i in 1:N){
	    a[j,i,k] ~ dnorm(mu[j],taub)
	  }
	}
	mu <- log(1 + 2)
}

**Comment by opcoach** [comment]
Duplicate issue of #13
