### ISSUE TITLE
mismatched input 'a' expected '}'

### ISSUE THREAD

**Issue by bhlbarxios** [opcoach/jagsy#2]
Wrong Error message : the variable name a in the model 
model{
  a ~ dnorm(1,1)
}
is identified as a mismatched character but shouldn't be....

**Comment by opcoach** [comment]
It is because, ID should have at least 2 characters... should be fixed !

**Comment by opcoach** [comment]
Fixed. The ID definition was not correct. Now it is possible to define ID with only 1 char
